general {
    lock_cmd = noctalia-shell ipc call lockScreen lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen after 7 minutes
listener {
    timeout = 420
    on-timeout = noctalia-shell ipc call lockScreen lock
}

# Turn off screen after 8 minutes
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off && brightnessctl s 0 -sd platform::kbd_backlight
    on-resume = hyprctl dispatch dpms on && brightnessctl -rd platform::kbd_backlight
}
