general {
    lock_cmd = noctalia msg session lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

# Lock screen after 7 minutes
listener {
    timeout = 420
    on-timeout = noctalia msg session lock
}

# Turn off screen after 8 minutes
listener {
    timeout = 480
    on-timeout =  hyprctl dispatch 'hl.dsp.dpms({ action = "off" })' && brightnessctl s 0 -sd platform::kbd_backlight
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && brightnessctl -rd platform::kbd_backlight
}
