input {
    kb_layout = us
    kb_options = #ctrl:nocaps
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35
  #follow_mouse = 0

    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
	clickfinger_behavior = 1
	tap-to-click = false
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    no_warps = true
}

device[ven_2c2f:00-2c2f:002b-touchpad]:enabled = true
